export const CREATE_TRANSACTION = "CREATE_TRANSACTION"
export const SET_LOADING = "SET_LOADING"
export const GET_TRANSACTIONS = "GET_TRANSACTIONS"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"