// TRANSACTION RELATED
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const SET_LOADING = "SET_LOADING";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_TRANSACTIONS_BY_YEAR = "GET_TRANSACTIONS_BY_YEAR";
export const CLEAR_TRANSACTIONS_BY_YEAR = "CLEAR_TRANSACTIONS_BY_YEAR";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const SET_CURRENT_TRANSACTION = "SET_CURRENT_TRANSACTION";
export const CLEAR_CURRENT_TRANSACTION = "CLEAR_CURRENT_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const SORT_TRANSACTIONS_DESC = "SORT_TRANSACTIONS_DESC";
export const SORT_TRANSACTIONS_ASC = "SORT_TRANSACTIONS_ASC";
export const SORT_TRANSACTIONS_BY_NAME = "SORT_TRANSACTIONS_BY_NAME";
export const SORT_TRANSACTIONS_BY_CATEGORY = "SORT_TRANSACTIONS_BY_CATEGORY";
export const GET_TRANSACTION_CATEGORIES = "GET_TRANSACTION_CATEGORIES"
export const ADD_TRANSACTION_CATEGORY = "ADD_TRANSACTION_CATEGORY"
export const DELETE_TRANSACTION_CATEGORY = "DELETE_TRANSACTION_CATEGORY"
export const UPDATE_TRANSACTION_CATEGORY = "UPDATE_TRANSACTION_CATEGORY"

// TIMEINTERVALL RELATED
export const SET_TIMEINTERVALL = "SET_TIMEINTERVALL";
export const GET_TIMESPANS = "GET_TIMESPANS";
export const ADD_TIMESPAN = "ADD_TIMESPAN";
export const REMOVE_TIMESPAN = "REMOVE_TIMESPAN";
export const REMOVE_TIMEINTERVAL_TRANSACTION = "REMOVE_TIMEINTERVAL_TRANSACTION";
export const FLUSH_TIMEINTERVALLS = "FLUSH_TIMEINTERVALLS";
export const SET_CURRENT_TIMEINTERVAL = "SET_CURRENT_TIMEINTERVAL";
export const CLEAR_CURRENT_TIMEINTERVAL = "CLEAR_CURRENT_TIMEINTERVAL";
export const UPDATE_TIMEINTERVAL = "UPDATE_TIMEINTERVAL";
export const SORT_TIMEINTERVALS_ASC = "SORT_TIMEINTERVALS_ASC";
